// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: enum/enum.proto

package enum

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Country int32

const (
	Country_NONE Country = 0 // 占位符，无意义
	Country_MY   Country = 1 // my
	Country_ID   Country = 2 // id
	Country_TH   Country = 3 // th
)

// Enum value maps for Country.
var (
	Country_name = map[int32]string{
		0: "NONE",
		1: "MY",
		2: "ID",
		3: "TH",
	}
	Country_value = map[string]int32{
		"NONE": 0,
		"MY":   1,
		"ID":   2,
		"TH":   3,
	}
)

func (x Country) Enum() *Country {
	p := new(Country)
	*p = x
	return p
}

func (x Country) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Country) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_enum_proto_enumTypes[0].Descriptor()
}

func (Country) Type() protoreflect.EnumType {
	return &file_enum_enum_proto_enumTypes[0]
}

func (x Country) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Country.Descriptor instead.
func (Country) EnumDescriptor() ([]byte, []int) {
	return file_enum_enum_proto_rawDescGZIP(), []int{0}
}

var File_enum_enum_proto protoreflect.FileDescriptor

var file_enum_enum_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x65, 0x6e, 0x75, 0x6d, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x2a, 0x2b, 0x0a, 0x07, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02,
	0x4d, 0x59, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x44, 0x10, 0x02, 0x12, 0x06, 0x0a, 0x02,
	0x54, 0x48, 0x10, 0x03, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x68, 0x61, 0x72, 0x6b, 0x6c, 0x69, 0x2f, 0x62, 0x32, 0x63, 0x2d, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x65, 0x6e, 0x75, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_enum_enum_proto_rawDescOnce sync.Once
	file_enum_enum_proto_rawDescData = file_enum_enum_proto_rawDesc
)

func file_enum_enum_proto_rawDescGZIP() []byte {
	file_enum_enum_proto_rawDescOnce.Do(func() {
		file_enum_enum_proto_rawDescData = protoimpl.X.CompressGZIP(file_enum_enum_proto_rawDescData)
	})
	return file_enum_enum_proto_rawDescData
}

var file_enum_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enum_enum_proto_goTypes = []interface{}{
	(Country)(0), // 0: enum.Country
}
var file_enum_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_enum_proto_init() }
func file_enum_enum_proto_init() {
	if File_enum_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_enum_enum_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_enum_proto_goTypes,
		DependencyIndexes: file_enum_enum_proto_depIdxs,
		EnumInfos:         file_enum_enum_proto_enumTypes,
	}.Build()
	File_enum_enum_proto = out.File
	file_enum_enum_proto_rawDesc = nil
	file_enum_enum_proto_goTypes = nil
	file_enum_enum_proto_depIdxs = nil
}
