// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.8
// source: translate/translate.proto

package translate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranslateIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TranslateParams []string `protobuf:"bytes,1,rep,name=translateParams,proto3" json:"translateParams,omitempty"`
	Country         int32    `protobuf:"varint,2,opt,name=country,proto3" json:"country,omitempty"`
}

func (x *TranslateIn) Reset() {
	*x = TranslateIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translate_translate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslateIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateIn) ProtoMessage() {}

func (x *TranslateIn) ProtoReflect() protoreflect.Message {
	mi := &file_translate_translate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateIn.ProtoReflect.Descriptor instead.
func (*TranslateIn) Descriptor() ([]byte, []int) {
	return file_translate_translate_proto_rawDescGZIP(), []int{0}
}

func (x *TranslateIn) GetTranslateParams() []string {
	if x != nil {
		return x.TranslateParams
	}
	return nil
}

func (x *TranslateIn) GetCountry() int32 {
	if x != nil {
		return x.Country
	}
	return 0
}

type TranslateOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TranslateResult map[string]string `protobuf:"bytes,1,rep,name=translateResult,proto3" json:"translateResult,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *TranslateOut) Reset() {
	*x = TranslateOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_translate_translate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TranslateOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranslateOut) ProtoMessage() {}

func (x *TranslateOut) ProtoReflect() protoreflect.Message {
	mi := &file_translate_translate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranslateOut.ProtoReflect.Descriptor instead.
func (*TranslateOut) Descriptor() ([]byte, []int) {
	return file_translate_translate_proto_rawDescGZIP(), []int{1}
}

func (x *TranslateOut) GetTranslateResult() map[string]string {
	if x != nil {
		return x.TranslateResult
	}
	return nil
}

var File_translate_translate_proto protoreflect.FileDescriptor

var file_translate_translate_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x22, 0x51, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x22, 0xaa, 0x01, 0x0a, 0x0c, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x12, 0x56, 0x0a, 0x0f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x4f, 0x75, 0x74, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x1a, 0x42, 0x0a, 0x14, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x49, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c,
	0x61, 0x74, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x1a, 0x17, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x65, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x4f, 0x75,
	0x74, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x68, 0x61, 0x72, 0x6b, 0x6c, 0x69, 0x2f, 0x62, 0x32, 0x63, 0x2d, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_translate_translate_proto_rawDescOnce sync.Once
	file_translate_translate_proto_rawDescData = file_translate_translate_proto_rawDesc
)

func file_translate_translate_proto_rawDescGZIP() []byte {
	file_translate_translate_proto_rawDescOnce.Do(func() {
		file_translate_translate_proto_rawDescData = protoimpl.X.CompressGZIP(file_translate_translate_proto_rawDescData)
	})
	return file_translate_translate_proto_rawDescData
}

var file_translate_translate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_translate_translate_proto_goTypes = []interface{}{
	(*TranslateIn)(nil),  // 0: translate.TranslateIn
	(*TranslateOut)(nil), // 1: translate.TranslateOut
	nil,                  // 2: translate.TranslateOut.TranslateResultEntry
}
var file_translate_translate_proto_depIdxs = []int32{
	2, // 0: translate.TranslateOut.translateResult:type_name -> translate.TranslateOut.TranslateResultEntry
	0, // 1: translate.Translate.Translate:input_type -> translate.TranslateIn
	1, // 2: translate.Translate.Translate:output_type -> translate.TranslateOut
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_translate_translate_proto_init() }
func file_translate_translate_proto_init() {
	if File_translate_translate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_translate_translate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslateIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_translate_translate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TranslateOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_translate_translate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translate_translate_proto_goTypes,
		DependencyIndexes: file_translate_translate_proto_depIdxs,
		MessageInfos:      file_translate_translate_proto_msgTypes,
	}.Build()
	File_translate_translate_proto = out.File
	file_translate_translate_proto_rawDesc = nil
	file_translate_translate_proto_goTypes = nil
	file_translate_translate_proto_depIdxs = nil
}
