// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: translate/translate.proto

package translate

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Translate service

func NewTranslateEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Translate service

type TranslateService interface {
	Translate(ctx context.Context, in *TranslateIn, opts ...client.CallOption) (*TranslateOut, error)
}

type translateService struct {
	c    client.Client
	name string
}

func NewTranslateService(name string, c client.Client) TranslateService {
	return &translateService{
		c:    c,
		name: name,
	}
}

func (c *translateService) Translate(ctx context.Context, in *TranslateIn, opts ...client.CallOption) (*TranslateOut, error) {
	req := c.c.NewRequest(c.name, "Translate.Translate", in)
	out := new(TranslateOut)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Translate service

type TranslateHandler interface {
	Translate(context.Context, *TranslateIn, *TranslateOut) error
}

func RegisterTranslateHandler(s server.Server, hdlr TranslateHandler, opts ...server.HandlerOption) error {
	type translate interface {
		Translate(ctx context.Context, in *TranslateIn, out *TranslateOut) error
	}
	type Translate struct {
		translate
	}
	h := &translateHandler{hdlr}
	return s.Handle(s.NewHandler(&Translate{h}, opts...))
}

type translateHandler struct {
	TranslateHandler
}

func (h *translateHandler) Translate(ctx context.Context, in *TranslateIn, out *TranslateOut) error {
	return h.TranslateHandler.Translate(ctx, in, out)
}
